
// soundcloud

module.exports = {
  kind: String,
  // id: String,
  // created_at: String,
  user_id: Number,
  duration: Number,
  commentable: String,
  state: String,
  original_content_size: Number,
  sharing: String,
  tag_list: String,
  permalink: String,
  streamable: String,
  embeddable_by: String,
  downloadable: String,
  purchase_url: String,
  label_id: String,
  purchase_title: String,
  genre: String,
  title: String,
  description: String,
  label_name: String,
  release: String,
  track_type: String,
  key_signature: String,
  isrc: String,
  video_url: String,
  bpm: String,
  release_year: String,
  release_month: String,
  release_day: String,
  original_format: String,
  license: String,
  uri: String,
  user: {
    id: Number,
    kind: String,
    permalink: String,
    username: String,
    uri: String,
    permalink_url: String,
    avatar_url: String
  },
  permalink_url: String,
  artwork_url: String,
  waveform_url: String,
  stream_url: String,
  playback_count: Number,
  download_count: Number,
  favoritings_count: Number,
  comment_count: Number,
  attachments_uri: String
};
